### ISSUE TITLE
Tracking loader support

### ISSUE THREAD

**Issue by hyf0** [rolldown/rolldown#1295]
- [x] js
- [x] jsx
- [x] ts
- [x] tsx
- [x] https://github.com/rolldown/rolldown/issues/1297
- [x] #1301
- [x] css
- [ ] Support copy loader
- [x] #1299
- [x] #1298
- [x] https://github.com/rolldown/rolldown/pull/2567
- [x] #1300
- [x] Support json loader
- [ ] ~Support local-css loader~
- [x] ~Support css loader~
- [ ] ~Support default loader~

---

- Contribution accepted tasks are already created. if some task is not mark as contribution-welcome, it means this task need to be implemented by rolldown's developer due to potential changes on the core architecture.
- ~Supporting for css is still delayed for now.~

**Comment by hyf0** [comment]
jsx, ts and tsx are supported in #1364.

**Comment by nicksrandall** [comment]
Why is CSS loader delayed? I was thinking that could be a good task for me to tackle but it sounds like we're not ready for that feature yet?

**Comment by hyf0** [comment]
> Why is CSS loader delayed? I was thinking that could be a good task for me to tackle but it sounds like we're not ready for that feature yet?

It requires quite of work to support it via loaders. A lot of core code might need to be changed. So we currently want support css via the plugin system rather than loaders.

**Comment by AliceLanniste** [comment]
Hi @hyf0, the file and copy loader implementations,  whether or not a `file module` converted into a chunk with`chunkKind::Common` in the `GenerateStage.generateChunk`

**Comment by hyf0** [comment]
> Hi @hyf0, the file and copy loader implementations, whether or not a `file module` converted into a chunk with`chunkKind::Common` in the `GenerateStage.generateChunk`

It won't

**Comment by AliceLanniste** [comment]
> > Hi @hyf0, the file and copy loader implementations, whether or not a `file module` converted into a chunk with`chunkKind::Common` in the `GenerateStage.generateChunk`
> 
> It won't

so can you explain the logic of  the file and copy loader implementations

**Comment by hyf0** [comment]
I so far don't have the bandwidth to write a detail explanation in text.

You should able to get some hint in 
 https://github.com/rolldown/rolldown/blob/f535ab201a3116bc2fd55a94c893b062cbf1af6b/crates/rolldown/src/asset/asset_generator.rs.

**Comment by AliceLanniste** [comment]
> I so far don't have the bandwidth to write a detail explanation in text.
> 
> You should able to get some hint in [`f535ab2`/crates/rolldown/src/asset/asset_generator.rs](https://github.com/rolldown/rolldown/blob/f535ab201a3116bc2fd55a94c893b062cbf1af6b/crates/rolldown/src/asset/asset_generator.rs).
thank you

**Comment by hyf0** [comment]
Except for `copy-loader`, required loaders are supported now.

**Comment by hyf0** [comment]
`copy` loader is under consideration. Meantime people who want to use it could try https://www.npmjs.com/package/rollup-plugin-copy.

**Comment by hi-ogawa** [comment]
Esbuild's copy loader https://esbuild.github.io/content-types/#copy is not `rollup-plugin-copy` but it's `keepImport` mode of `rollup-plugin-smart-asset` https://github.com/sormy/rollup-plugin-smart-asset?tab=readme-ov-file#mode-copy.

I haven't tested the plugin but the minimal version looks like this https://stackblitz.com/edit/rolldown-rolldown-starter-stackblitz-thywhnvs?file=rolldown.config.mjs The idea is to use `resolveId` to externalize assets import with placeholder of `emitFile` reference id and replace it during `renderChunk` with a final asset path.

```js
import { defineConfig } from 'rolldown';
import path from 'node:path';
import fs from 'node:fs';

export default defineConfig({
  input: ['./src/entry.js'],
  moduleTypes: {
    svg: 'js',
  },
  plugins: [
    {
      name: 'copy-loader-svg',
      resolveId: {
        filter: /\.svg$/,
        async handler(source, importer, extraOptions) {
          if (!source.endsWith('.svg')) return;

          const resolved = await this.resolve(source, importer, extraOptions);
          if (resolved) {
            const referenceId = this.emitFile({
              type: 'asset',
              name: path.basename(resolved.id),
              source: fs.readFileSync(resolved.id),
            });
            return {
              id: '__copy_placeholder__:' + referenceId,
              external: true,
            };
          }
        },
      },
      renderChunk(code, chunk) {
        if (code.includes('__copy_placeholder__:')) {
          return code.replace(/__copy_placeholder__:(\w+)/g, (_match, id) => {
            const assetFile = this.getFileName(id);
            const relative = path.relative(
              path.join(chunk.fileName, '..'),
              assetFile
            );
            return './' + relative;
          });
        }
      },
    },
  ],
});
```
