### ISSUE TITLE
Milestone 1: replace esbuild with rolldown in vite

### ISSUE THREAD

**Issue by underfin** [rolldown/rolldown#15]
# POC 1

- [x] #22
- [x] #18
- [x] #16
- [x] #35
- [x] #36
- [x] https://github.com/rolldown-rs/rolldown/issues/113

# POC 2
- [ ] support `format: cjs` 
- [x] node binding
  - [ ] plugin & plugin driver
- [ ] hash support
- [ ] complete supporting for  external module
- [ ] chunk hash
# 
- [x] module graph
- [x] esm syntax ast scan & linking imports/exports
- [x] module render with ast mutaition and ast codegen (symbol deconflict)
- [x] chunk render with concat module ast codegen result
- [x] #17
- [ ] glob import
- [ ] ci release build
- [x] [simple benchmark](https://github.com/rolldown-rs/rolldown/pull/19)
- [ ] more esbuild/rollup test migrate
- [ ] options

**Comment by hyf0** [comment]
Closed as outdated. Create an new one if we still need to track this.
