### ISSUE TITLE
Rollup APIs used by Vite

### ISSUE THREAD

**Issue by underfin** [rolldown/rolldown#1554]
Rolldown need to support some api for vite build.

- [x] build watch
- [x] https://github.com/rolldown/rolldown/issues/3500
- [x] [input.exports 'auto'](https://github.com/rolldown/rolldown/issues/1628)
- [x] #1728
- [x] output.name (library)
- [ ] output.hoistTransitiveImports (import code import performance)
- [x] https://github.com/rolldown/rolldown/issues/206
- [x] #1841
- [x] [output.format umd (ssr or library build )](https://github.com/rolldown/rolldown/pull/2489)
- [x] #2355
- [x] PluginContext#resolveId skipSelf
- [x] https://github.com/rolldown/rolldown/pull/769 ( src/node/plugins/index.ts:157:18  getSortedPluginsByHook)

**Comment by IWANABETHATGUY** [comment]
It seems we already support ` PluginContext#load` and 
` PluginContext#resolveId skipSelf`?

**Comment by 7086cmd** [comment]
It appears that the `hoistTransitiveImports` option is currently set to false by default in Rolldown’s behavior (related: rollup/rollup#3332). Is it necessary to support the option being set to `true`?

**Comment by sapphi-red** [comment]
I think we can close this issue now as rolldown-vite is not blocked by rolldown.
