### ISSUE TITLE
Tracking CSS loader support

### ISSUE THREAD

**Issue by 7086cmd** [rolldown/rolldown#1598]
### What problem does this feature solve?

Although #1295 announced that the CSS loader may be delayed, tracking the roadmap for supporting CSS is a good chance to track the support for spare loaders [e.g. [file, copy (which is called at "External File" in `esbuild`)](https://esbuild.github.io/content-types/#external-file)].

### What does the proposed API look like?

The key point for supporting these loaders is a way to branch out non-Ecma module types (e.g. CSS, static files, etc.). So, I think the CSS support requires the following steps (it may take a long time):

### Pre-support Steps
- [x] Rename all `Normal` into `Ecma` to separate different module types. (in #1551)
- [ ] Add `Css` as modules and loaders and leave `todo!` in syntax matches. (in #1572)
- [ ] Use `lightningcss` crate to parse codes into AST. (in #1572)

### Support Steps
- [ ] Create an elegant way to distribute static files apart from Ecma Modules, including static files (`copy`, etc. loaders and `CSS`, fonts). This can be also helpful for supporting `copy` and `file` loader).
- [ ] Support basic transform without bundling.

### Target Features
- [ ] Support directly bundling `CSS` files (refer to [esbuild](https://esbuild.github.io/content-types/#css-caveats), the `@import` syntax).
- [ ] Support globally importing `CSS` files in JavaScript / TypeScript files (refer to [esbuild](https://esbuild.github.io/content-types/#css-from-js)).
- [ ] Support partially importing `CSS` modules in JavaScript / TypeScript files (refer to [esbuild](https://esbuild.github.io/content-types/#local-css), it is so great).
- [ ] Distinguish import ways of importing `CSS` (refer to [the rollup plugin](https://www.npmjs.com/package/rollup-plugin-import-css), it can react classified, including regarding the module as a string when using `import style from "style.css"` or regarding the module as an external file when using `import "style.css"`).

Since I am still reading the core code, there may be wrongs, please figure them out :-)

By the way, the summer vacation starts! Now I am more available to read core codes :-).

**Comment by 7086cmd** [comment]
Should we use `lightningcss::bundler`? The shaking may not be so capable of Rolldown (imo), so is it better to manually analyze the AST via `lightningcss::stylesheet` and bundle it?

**Comment by Boshen** [comment]
Hi @7086cmd, your friend told us about you during Vue Conf dinner, and we are sincerely amazed by your enthusiasm about this project. 

We thank you for taking the initiative of tracking css loader support, but unfortunately we are short staffed, and may not have enough focus and energy to guide you on this task.

We'll let you know when is the right time to start tackling css support. We promise it won't be long as we are in the process of revamping our architecture.

**Comment by hyf0** [comment]
To prevent misunderstanding of thinking this as an official tracking issue from others, I'm gonna close this one. Thanks for you attention.

**Comment by yyx990803** [comment]
@7086cmd just want to say we really appreciate your interest in contributing to Rolldown. I don't want us closing this issue to discourage your involvement, so I want to provide some extra reasoning / advice.

For large projects that have been going on for a while, It is usually not recommended for new contributors to directly own a significant feature (especially the planning part) like this. The reason for this is that significant features require a lot of context of how things work in the existing codebase. New contributors' assumptions can be missing considerations on existing constraints, and the more ambitious the proposal is, the more likely it contains ideas that conflict with what the team already have in mind. This would then require heavy communication overhead from existing contributors to reconcile the difference, and often end up wasting time for both sides.

We recommend new contributors to start with smaller, more concrete tasks to build up the context, trust, and familiarity with both the codebase and the project philosophy. This process will take time, but it will allow you to better align with the goal and plan of the project before jumping on bigger tasks in the future.

**Comment by 7086cmd** [comment]
Nevermind :) Thanks for your detailed advice and understanding. I apologize for any sudden actions and deeply appreciate the guidance. I hope to contribute more effectively in the future!
