### ISSUE TITLE
[Tracking]: prettify the build output

### ISSUE THREAD

**Issue by hyf0** [rolldown/rolldown#162]
"prettify the build output" is not the primary goal currently, the issue is only for recording.

- [x] #440
- [x] Empty wrapper should be in a single line
- [x] Merge import specifiers that import from the same module
- [x] remove empty statements
- [x] Remove meaningless lines of modules.
