### ISSUE TITLE
[Tracking] symbol deconflicting

### ISSUE THREAD

**Issue by hyf0** [rolldown/rolldown#189]
- [ ] Support keep class/function name after deconflicting
- [x] Non-top-level symbols in parallel scopes should not affects each others
- [x] https://github.com/rolldown-rs/rolldown/issues/190
- [x] https://github.com/rolldown-rs/rolldown/issues/191
- [x] #357
