### ISSUE TITLE
[Tracking] `ReplacePlugin`

### ISSUE THREAD

**Issue by hyf0** [rolldown/rolldown#2057]
`ReplacePlugin` https://github.com/rolldown/rolldown/pull/2056 is the builtin version of rolldown that align with `rollup-plugin-reaplce`.

## To be finished

- [x] Migrate all tests
  - Migrated: https://github.com/rolldown/rolldown/tree/1a5b2a3ebfa0e8e5bbb2e81eb33ed297a51788bf/crates/rolldown_plugin_replace/tests/form
  - To be migrated: https://github.com/rollup/plugins/tree/master/packages/replace/test/fixtures/form
- [x] Support `objectGuards` option
- [x] Support `preventAssignment` option
- [ ] Support sourcemap

References:

- https://github.com/rollup/plugins/blob/master/packages/replace/README.md

**Comment by ikkz** [comment]
Can I try this?

**Comment by hyf0** [comment]
Sure.

**Comment by vhfmag** [comment]
Hi @hyf0! I'm taking a look into this issue and I'm seeing this error when trying to use `MagicString::source_map` to generate a source map:

```
mismatched types
`oxc_sourcemap::sourcemap::SourceMap` and `oxc_sourcemap::sourcemap::SourceMap` have similar names, but are actually distinct types
perhaps two different versions of crate `oxc_sourcemap` are being used?rustc[Click for full compiler diagnostic](rust-analyzer-diagnostics-view:/diagnostic message [0]?0#file:///Users/vmagalhaes/dev/rolldown/crates/rolldown_plugin_replace/src/plugin.rs)
```

This seems to happen because the latest `magic_string` depends on `oxc_sourcemap` 0.25.0, while rolldown itself depends on `oxc_sourcemap` 0.31.0. I just thought I'd check if generating a source map with `MagicString::source_map` seems like a good plan so that I can look into upgrading `oxc_sourcemap` in `magic_string`. Thanks!
