### ISSUE TITLE
[Tracking] Milestone2: rollup compatibility

### ISSUE THREAD

**Issue by hyf0** [rolldown/rolldown#334]
TODO: more descriptions

- [x] https://github.com/rolldown-rs/rolldown/issues/45
- [ ]  Support`InputOptions#onwarn`.

## Plugin compat

- [ ] `@rollup/plugin-typescript`
- [ ] 

## Misc

- [ ] First class support for bundling json
- [ ] First class support for data-url
