### ISSUE TITLE
[Tracking] Rollup Plugin Compat Status

### ISSUE THREAD

**Issue by underfin** [rolldown/rolldown#819]
### Fully Supported Hooks

- [x] `options`
- [x] `buildStart`
- [x] `buildEnd`
- [x] `renderStart`
- [x] `renderError`
- [x] `generateBundle`
- [x] `writeBundle`
- [x] `closeBundle`
- [x] `banner`
- [x] `footer`
- [x] `intro`
- [x] `outro`
- [x] `augmentChunkHash`
- [x] `closeWatcher`
- [x] `watchChange`
- [x] `renderChunk`

## Partually Supported Hooks

Hooks in this section can work as intended for most commonly seen plugins, but they may have some niche options / behavior that are not implemented yet.

Our priority at this stage is implement enough compatibility for most plugins to run, and determine whether to support the niche options at a later stage based on user demand. Some options are explicitly marked as "will not support" due to architectural incompatibility and limited use case.

- `outputOptions`
  - the `PluginContext` is not supported yet.
- `resolveId`
  - the 3rd argument `options.attributes` is not supported yet
  - the following fileds in the return value are not supported yet:
    - `attributes`
    - `resolvedBy`
    - `syntheticNamedExports`
- `load`
  - the following fileds in the return value are not supported yet:
    - `attributes`
    - `syntheticNamedExports`
    - `ast` <sup>will not support</sup>
- `transform`
  - the following fileds in the return value are not supported yet:
    - `attributes`
    - `syntheticNamedExports`
    - `ast` <sup>will not support</sup>
- `moduleParsed`
  - the argument `moduleInfo` is only partially compatible
- `resolveDynamicImport`
  - the 3rd argument `options.attributes` is not supported yet
- `onLog`
  - the `meta` property is not supported yet

### Not Yet Supported

- [ ] `shouldTransformCachedModule`
- [ ] `resolveFileUrl`
- [ ] `resolveImportMeta`
- [ ] `renderDynamicImport`

### Supported Properties

- [x] `debug`
- [x] `error`
- [x] `info`
- [x] `warn`
- [x] `getFileName`
- [x] `getModuleIds`
- [x] `getModuleInfo`
- [x] `addWatchFile`
- [x] `getCombinedSourcemap`
- [x] `parse`

### Partially Supported Properties

- `resolve`
  - `options.isEntry` and `options.attributes` are not supported yet
- `emitFile`
  - only support emitting asset and chunk for now
- `load`
  - only support call at `resolved(not resolving entry ids)/load/transform` hooks

### Not Yet Supported Properties

- `meta`
- `cache`
- `getWatchFiles`
- `setAssetSource`

## Vite Internal Plugins Compatibility

- [x] `assetPlugin`.
- [x] `assetImportMetaUrlPlugin`
- [x] `clientInjectionsPlugin`
- [x] `completeSystemWrapPlugin`
- [x] `cssPlugin`
- [x] `cssPostPlugin`
- [x] `cssAnalysisPlugin`
- [x] `dataURIPlugin`
- [x] `definePlugin`
- [x] \*`dynamicImportVarsPlugin`
- [x] `esbuildPlugin`
- [x] `buildEsbuildPlugin`
- [x] `htmlInlineProxyPlugin`
- [x] `buildHtmlPlugin`
- [x] `importAnalysisPlugin`
- [x] `buildImportAnalysisPlugin`
- [ ] `importGlobPlugin` - needs `resolveId#option` the argument fileds `attributes` 
- [x] `jsonPlugin`
- [x] `loadFallbackPlugin` 
- [x] `manifestPlugin`
- [x] `metadataPlugin` , needs mutate( add extra fileds) `renderChunkArgs#RenderedChunk` and using it at `augmentChunkHash/generateBundle`, it rewrite to stored at js side.
- [x] `modulePreloadPolyfillPlugin`
- [x] `optimizedDepsPlugin`
- [x] `preAliasPlugin`
- [x] `buildReporterPlugin`
- [x] `resolvePlugin`
- [ ] `splitVendorChunkPlugin` - needs `manualChunks`. @deprecated
- [x] `terserPlugin`
- [x] `wasmFallbackPlugin`
- [x] `wasmHelperPlugin`
- [ ] `webWorkerPostPlugin` - needs `resolveImportMeta`
- [x] `webWorkerPlugin` - needs `shouldTransformCachedModule`
- [x] `workerImportMetaUrlPlugin` - needs `shouldTransformCachedModule`
- [x] `ssrManifestPlugin`

## Vite Public Plugins Compatibility

- [x] `@vitejs/plugin-vue`
- [x] `@vitejs/plugin-vue-jsx`
- [x] `@vitejs/plugin-react`

### Supported as Built-in

The following Rollup plugins are no longer needed because Rolldown offers built-in support for equivalent features:

- `@rollup/plugin-alias` - use `resolve.alias` option instead.
- `@rollup/plugin-commonjs` - Rolldown has built-in support
- `@rollup/plugin-inject` - use `inject` option instead.
- `@rollup/plugin-node-resolve` - Rolldown has built-in support
- `@rollup/plugin-json` - Rolldown has built-in support
- `@rollup/plugin-replace` - Rolldown provides built-in support via `import { replacePlugin } from 'rolldown/experimental'`
- `@rollup/plugin-swc`, `@rollup/plugin-babel`, `@rollup/plugin-sucrase` - Rolldown has built-in TS / JSX transform support via Oxc. Target-lowering transforms are WIP.
- `@rollup/plugin-dynamic-import-vars` , Rolldown provides built-in support via `import { dynamicImportVarsPlugin } from 'rolldown/experimental'`.

### Fully Compatible Plugins

- [x] `@rollup/plugin-auto-install`
- [x] `@rollup/plugin-beep`
- [x] `@rollup/plugin-data-uri`
- [x] `@rollup/plugin-dsv`
- [x] `@rollup/plugin-eslint` - consider using `oxlint` instead
- [x] `@rollup/plugin-esm-shim`
- [x] `@rollup/plugin-graphql`
- [x] `@rollup/plugin-legacy`
- [x] `@rollup/plugin-run`
- [x] `@rollup/plugin-terser` - Rolldown has built-in minifcation via `output.minify` option, but it's still WIP
- [x] `@rollup/plugin-virtual` -
- [x] `@rollup/plugin-yaml`
- [x] `@rollup/plugin-multi-entry` 
- [x] `@rollup/plugin-image`
- [x] `@rollup/plugin-url` 
- [x] `@rollup/plugin-wasm` will likely have built-in support
- [x] `@rollup/plugin-html`
- [x] `@rollup/plugin-buble`
- [x] `@rollup/plugin-strip` 
### Not Yet Compatible

- [ ] `@rollup/plugin-typescript`  - Rolldown will support emitting bundled dts with `isolatedDeclarations: true` in the future

### [analog](https://github.com/analogjs/analog)

- [ ] `jitPlugin` - needs find plugin by plugin name at `buildStart` options, then using the plugin `transform`, see [here](https://github.com/analogjs/analog/blob/beta/packages/vite-plugin-angular/src/lib/angular-jit-plugin.ts#L25)

### [astro](https://github.com/withastro/astro)

- [ ] `astroScannerPlugin` - needs using `PluginContext#getModuleInfo` as `TransformResult#meta`, see [here](https://github.com/withastro/astro/blob/main/packages/astro/src/vite-plugin-scanner/index.ts#L63), (todo find usage)
- [x] `markdown` - needs `LoadResult#meta`
- [x] `html` - needs mutate `NormalizedOption#plugins` at `options` hook, see [here](https://github.com/withastro/astro/blob/main/packages/astro/src/vite-plugin-html/index.ts#L7)
- [ ] `astroHeadBuildPlugin` - needs mutate `ModuleInfo#meta` using `PluginContext#getModuleInfo` at generateBundle hook, see [here](https://github.com/withastro/astro/blob/main/packages/astro/src/vite-plugin-head/index.ts#L127)
- [ ] `postprocess` direct using `acorn#parse`
- [ ] `vitePluginAnalyzer` using `ModuleInfo#meta` by `PluginContext#getModuleIds/getModuleInfo` at generateBundle hook, see [here](https://github.com/withastro/astro/blob/main/packages/astro/src/core/build/plugins/plugin-analyzer.ts#L126)
- [ ] `vitePluginContent` mutate `NormalizedOption#input` at `options` hook, see [here](https://github.com/withastro/astro/blob/main/packages/astro/src/core/build/plugins/plugin-content.ts#L104), mutate `NormalizedOption#manualChunks` at same file
- [ ] `css` TODO
- [x] `import.meta.ROLLUP_FILE_URL_*`

### [histoire](https://github.com/histoire-dev/histoire)

mutate `NormalizedOption#external`(look like is not correct), see [here](https://github.com/histoire-dev/histoire/blob/main/packages/histoire/src/node/build.ts#L101)

### [qwik](https://github.com/QwikDev/qwik)

`qwikCityPlugin` used `moduleSideEffect: no-treeshake`, see [here](https://github1s.com/QwikDev/qwik/blob/main/packages/qwik-city/buildtime/vite/plugin.ts#L37)

**Comment by sapphi-red** [comment]
`import.meta.ROLLUP_FILE_URL_*` needs to be supported as well:
https://stackblitz.com/edit/github-6jajke-dkf5gh?file=rolldown.config.mjs

It seems astro uses it: https://github.com/withastro/astro/blob/1c64ae304d3c008a776e98e48fd3ece8be7b1fb5/packages/db/src/core/integration/file-url.ts#L32

**Comment by YurySolovyov** [comment]
Any chance for `exports` on `ModuleInfo` ? E.g. on `moduleParsed` callback, or on `this.getModuleInfo(id)`

**Comment by underfin** [comment]
> Any chance for `exports` on `ModuleInfo` ? E.g. on `moduleParsed` callback, or on `this.getModuleInfo(id)`

@YurySolovyov It's a low priority at our roadmap. Could you give me some plugins using it? we could discuss it and pick it up.

**Comment by YurySolovyov** [comment]
@underfin 
TBH, I was looking for it while implementing my own plugin. Didn't do any research on other plugins.
If it is a low priority for the team, would it make a difference if I try to implement it on my own and submit a PR?

**Comment by underfin** [comment]
> [@underfin](https://github.com/underfin) TBH, I was looking for it while implementing my own plugin. Didn't do any research on other plugins. If it is a low priority for the team, would it make a difference if I try to implement it on my own and submit a PR?

track it at here https://github.com/rolldown/rolldown/issues/3168

**Comment by jdvivar** [comment]
@underfin the PluginContext heading says `parse` won't be supported:
> parse (will not support)

but on the compatible plugins list it says:
> @rollup/plugin-dynamic-import-vars using PluginContext#parse, will have built-in support

Can you clarify? Thanks!

EDIT:
After a second thought, I think it means we won't need the `@rollup/plugin-dynamic-import-vars` as rolldown will cover its functionality built-in without a plugin, is that right?

**Comment by underfin** [comment]
> [@underfin](https://github.com/underfin) the PluginContext heading says `parse` won't be supported:
> 
> > parse (will not support)
> 
> but on the compatible plugins list it says:
> 
> > @rollup/plugin-dynamic-import-vars using PluginContext#parse, will have built-in support
> 
> Can you clarify? Thanks!
> 
> EDIT: After a second thought, I think it means we won't need the `@rollup/plugin-dynamic-import-vars` as rolldown will cover its functionality built-in without a plugin, is that right?

Rolldown provides built-in support via `import { dynamicImportVarsPlugin } from 'rolldown/experimental'`. You could using it.

**Comment by GauBen** [comment]
Hi! The [closeBundle](https://rollupjs.org/plugin-development/#closebundle) hook may receive the build error since [#5867](https://github.com/rollup/rollup/pull/5867)

**Comment by underfin** [comment]
> Hi! The [closeBundle](https://rollupjs.org/plugin-development/#closebundle) hook may receive the build error since [#5867](https://github.com/rollup/rollup/pull/5867)

let's tracking at here https://github.com/rolldown/rolldown/issues/4364

**Comment by Boshen** [comment]
All features required by Vite is now completed.

Close as stale because we stopped tracking in this issue.

Feel free to raise an issue if you find missing features.
